### ISSUE TITLE
After regexp change merge, optimization triggers a bug

### ISSUE THREAD

**Issue by mmikulicic** [cesanta/v7#399]
After #395 :

```
make: Entering directory '/cesanta/v7/tests'
CC      unit_test_msan
RUN     unit_test_msan
==36== WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7ff995e5769e in v7_get_own_property2 /cesanta/v7/tests/../src/vm.c:569:14
    #1 0x7ff995e5846b in v7_get_own_property /cesanta/v7/tests/../src/vm.c:596:10
    #2 0x7ff995e586c5 in v7_get_property /cesanta/v7/tests/../src/vm.c:606:17
    #3 0x7ff995e96e16 in i_eval_expr /cesanta/v7/tests/../src/interpreter.c:414:14
    #4 0x7ff995e91962 in i_eval_stmt /cesanta/v7/tests/../src/interpreter.c:1474:13
    #5 0x7ff995e87ac0 in i_eval_stmts /cesanta/v7/tests/../src/interpreter.c:1048:11
    #6 0x7ff995e87527 in i_invoke_function /cesanta/v7/tests/../src/interpreter.c:912:9
    #7 0x7ff995ea3345 in i_eval_call /cesanta/v7/tests/../src/interpreter.c:1033:9
    #8 0x7ff995e9c379 in i_eval_expr /cesanta/v7/tests/../src/interpreter.c:635:13
    #9 0x7ff995e90f61 in i_eval_stmt /cesanta/v7/tests/../src/interpreter.c:1446:13
    #10 0x7ff995e87ac0 in i_eval_stmts /cesanta/v7/tests/../src/interpreter.c:1048:11
    #11 0x7ff995e87527 in i_invoke_function /cesanta/v7/tests/../src/interpreter.c:912:9
    #12 0x7ff995ea3345 in i_eval_call /cesanta/v7/tests/../src/interpreter.c:1033:9
    #13 0x7ff995e9c379 in i_eval_expr /cesanta/v7/tests/../src/interpreter.c:635:13
    #14 0x7ff995e942a0 in i_eval_expr /cesanta/v7/tests/../src/interpreter.c:270:12
    #15 0x7ff995e8a2ae in i_eval_stmt /cesanta/v7/tests/../src/interpreter.c:1082:26
    #16 0x7ff995e87ac0 in i_eval_stmts /cesanta/v7/tests/../src/interpreter.c:1048:11
    #17 0x7ff995e87527 in i_invoke_function /cesanta/v7/tests/../src/interpreter.c:912:9
    #18 0x7ff995ea3345 in i_eval_call /cesanta/v7/tests/../src/interpreter.c:1033:9
    #19 0x7ff995e9c379 in i_eval_expr /cesanta/v7/tests/../src/interpreter.c:635:13
    #20 0x7ff995e91962 in i_eval_stmt /cesanta/v7/tests/../src/interpreter.c:1474:13
    #21 0x7ff995e87ac0 in i_eval_stmts /cesanta/v7/tests/../src/interpreter.c:1048:11
    #22 0x7ff995e89f46 in i_eval_stmt /cesanta/v7/tests/../src/interpreter.c:1075:13
    #23 0x7ff995e8874e in v7_exec_with /cesanta/v7/tests/../src/interpreter.c:1594:7
    #24 0x7ff995e91b8d in v7_exec /cesanta/v7/tests/../src/interpreter.c:1608:10
    #25 0x7ff995e1548a in test_ecmac /cesanta/v7/tests/unit_test.c:1023:11
    #26 0x7ff995dbf03c in run_all_tests /cesanta/v7/tests/unit_test.c:1971:3
    #27 0x7ff995dbd0ca in main /cesanta/v7/tests/unit_test.c:1981:26
    #28 0x7ff994c1fec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #29 0x7ff995d68a8e in _start (/cesanta/v7/tests/unit_test_msan+0x3aa8e)
```

**Comment by mmikulicic** [comment]
fixed in 2d099bc
